module.exports.descriptors = [
    "Wilderness",
    "Forest",
    "Canyon",
    "Lake",
    "River",
    "Mountain",
    "Valley",
    "Beach",
    "Desert",
    "Prairie",
    "Glacier",
    "Island",
    "Jungle",
    "Hilltop",
    "Meadow",
    "Oasis",
    "Creekside",
    "Woodland"
];

module.exports.places = [
    "Mountain Camp",
    "Forest Camp",
    "River Camp",
    "Desert Camp",
    "Beach Camp",
    "Lake Camp",
    "Valley Camp",
    "Canyon Camp",
    "Hilltop Camp",
    "Woodland Camp",
    "Prairie Camp",
    "Alpine Camp",
    "Coastal Camp",
    "Island Camp",
    "Jungle Camp",
    "Oasis Camp",
    "Tundra Camp",
    "Savanna Camp",
    "Rainforest Camp",
    "Polar Camp",
    "Volcano Camp"
];